/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project11;

import static java.awt.image.ImageObserver.HEIGHT;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author marah
 */
public class version2 extends javax.swing.JFrame {
    int total =21;
    ArrayList<String> ball = new ArrayList<String>();
    boolean flag1 =true;
    boolean flag2 =true;
    boolean flagcomputer =false;
    /**
     * Creates new form version2
     */
    public version2() {
        initComponents();      
        for (int i=0;i<21;i++){
            ball.add("ball"+(i+1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ball16 = new javax.swing.JLabel();
        ball20 = new javax.swing.JLabel();
        ball11 = new javax.swing.JLabel();
        ball12 = new javax.swing.JLabel();
        ball13 = new javax.swing.JLabel();
        ball14 = new javax.swing.JLabel();
        ball15 = new javax.swing.JLabel();
        ball19 = new javax.swing.JLabel();
        ball18 = new javax.swing.JLabel();
        ball17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ball1 = new javax.swing.JLabel();
        ball2 = new javax.swing.JLabel();
        ball3 = new javax.swing.JLabel();
        ball4 = new javax.swing.JLabel();
        ball10 = new javax.swing.JLabel();
        ball9 = new javax.swing.JLabel();
        ball8 = new javax.swing.JLabel();
        ball7 = new javax.swing.JLabel();
        ball6 = new javax.swing.JLabel();
        ball5 = new javax.swing.JLabel();
        ball21 = new javax.swing.JLabel();
        newgame = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back1.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back1.jpg"))); // NOI18N
        jLabel17.setText("jLabel16");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back1.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hhhhhhh.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/qqq1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        ball16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball16, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 256, -1, -1));

        ball20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball20, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 256, -1, -1));

        ball11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        ball12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball12, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 210, -1, -1));

        ball13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        ball14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball14, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 210, -1, -1));

        ball15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        ball19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball19, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 256, -1, -1));

        ball18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball18, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 256, -1, -1));

        ball17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball17, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 256, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/1ll.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 345, -1, 67));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/2k.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 352, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/compPlay.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        ball1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        ball2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        ball3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        ball4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        ball10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        ball9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        ball8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        ball7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        ball6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        ball5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        ball21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project11/ball11.png"))); // NOI18N
        jPanel1.add(ball21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        newgame.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newgame.setForeground(new java.awt.Color(255, 255, 255));
        newgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newGame.png"))); // NOI18N
        newgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newgameMouseClicked(evt);
            }
        });
        jPanel1.add(newgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));
        newgame.setVisible(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back1.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        info2 l = new info2();
        l.show();
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        int an=JOptionPane.showConfirmDialog(rootPane, " Are you sure to exit game?");
        if (an == 0){
             NewJFrame l = new NewJFrame();
             l.show();
             dispose();
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        if (flag1 =true){
            flag2 =false;
            flagcomputer =false;
            total-=1;
            for (int i=0; i<1; i++){
                hideball(ball.get(i));
            }
        }
        endgame();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
       if (flag2 =true){
            flag1 =false;
            flagcomputer =false;
        total-=2;
        int num =2;
        int i=0;
        while (i<num){
            String s=ball.get(i);
            hideball(s);
            num--;
        }
       }
       endgame();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here
        if (flagcomputer){
            JOptionPane.showMessageDialog(rootPane, "It is your turn");
        }
        else {
            flag1 =true;
            flag1 =true;
            flagcomputer =true;
            int choice=0;
            if (total % 2== 1) {
                choice = 1 + new Random().nextInt(2);
                } else {
                    choice = (total - 1) % 2;
                }
            int i=0;
            while (i<choice){
                String s=ball.get(i);
                hideball(s);
                choice--;
                }
        }
        endgame();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void newgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newgameMouseClicked
        // TODO add your handling code here:
        version2 jf = new version2();
        jf.show();
        dispose();
    }//GEN-LAST:event_newgameMouseClicked

    /**
     * @param args the command line arguments
     */
    private void hideball(String s) {
        switch (s) {
            case "ball1":
                ball1.setVisible(false);
                ball.remove(s);
                break;
            case "ball2":
                ball2.setVisible(false);
                ball.remove(s);
                break;
             case "ball3":
                ball3.setVisible(false);
                ball.remove(s);
                break;
             case "ball4":
                ball4.setVisible(false);
                ball.remove(s);
                break;
             case "ball5":
                ball5.setVisible(false);
                ball.remove(s);
                break;
             case "ball6":
                ball6.setVisible(false);
                ball.remove(s);
                break;
             case "ball7":
                ball7.setVisible(false);
                ball.remove(s);
                break;
             case "ball8":
                ball8.setVisible(false);
                ball.remove(s);
                break;
             case "ball9":
                ball9.setVisible(false);
                ball.remove(s);
                break;
            case "ball10":
                ball10.setVisible(false);
                ball.remove(s);
                break;
            case "ball11":
                ball11.setVisible(false);
                ball.remove(s);
                break;
            case "ball12":
                ball12.setVisible(false);
                ball.remove(s);
                break;
             case "ball13":
                ball13.setVisible(false);
                ball.remove(s);
                break;
             case "ball14":
                ball14.setVisible(false);
                ball.remove(s);
                break;
             case "ball15":
                ball15.setVisible(false);
                ball.remove(s);
                break;
             case "ball16":
                ball16.setVisible(false);
                ball.remove(s);
                break;
             case "ball17":
                ball17.setVisible(false);
                ball.remove(s);
                break;
             case "ball18":
                ball18.setVisible(false);
                ball.remove(s);
                break;
             case "ball19":
                ball19.setVisible(false);
                ball.remove(s);
                break;
            case "ball20":
                ball20.setVisible(false);
                ball.remove(s);
                break;
            case "ball21":
                ball21.setVisible(false);
                ball.remove(s);
                break;
        }
    }
    public void endgame(){
        Icon win = new javax.swing.ImageIcon(getClass().getResource("/icons/youwin.png"));
        Icon lose = new javax.swing.ImageIcon(getClass().getResource("/icons/youlose.png"));
        if (ball.isEmpty()){
            if (flagcomputer) JOptionPane.showMessageDialog(rootPane, " ", "", HEIGHT,win);
            else JOptionPane.showMessageDialog(rootPane, "", "", HEIGHT,lose); 
            jLabel1.setVisible(false);
            newgame.setVisible(true);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(version2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(version2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(version2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(version2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new version2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ball1;
    private javax.swing.JLabel ball10;
    private javax.swing.JLabel ball11;
    private javax.swing.JLabel ball12;
    private javax.swing.JLabel ball13;
    private javax.swing.JLabel ball14;
    private javax.swing.JLabel ball15;
    private javax.swing.JLabel ball16;
    private javax.swing.JLabel ball17;
    private javax.swing.JLabel ball18;
    private javax.swing.JLabel ball19;
    private javax.swing.JLabel ball2;
    private javax.swing.JLabel ball20;
    private javax.swing.JLabel ball21;
    private javax.swing.JLabel ball3;
    private javax.swing.JLabel ball4;
    private javax.swing.JLabel ball5;
    private javax.swing.JLabel ball6;
    private javax.swing.JLabel ball7;
    private javax.swing.JLabel ball8;
    private javax.swing.JLabel ball9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newgame;
    // End of variables declaration//GEN-END:variables
}
