/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author msys
 */
public class interface5 extends javax.swing.JFrame {

    /**
     * Creates new form interface5
     */
    public interface5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        signUp = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        guardianSSNLabel = new javax.swing.JLabel();
        guardianSSNTextField = new javax.swing.JTextField();
        guardianNameLabel = new javax.swing.JLabel();
        guardianNameTextField = new javax.swing.JTextField();
        SuppcardNumberLabel = new javax.swing.JLabel();
        suppCardNumberText = new javax.swing.JTextField();
        affCardNumberLabel = new javax.swing.JLabel();
        affCardNumberText = new javax.swing.JTextField();
        finish = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        signUp.setForeground(new java.awt.Color(77, 5, 77));
        signUp.setText("Sign Up Of Patient");
        jPanel1.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\ICON.png")); // NOI18N
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\BACK.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        guardianSSNLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        guardianSSNLabel.setForeground(new java.awt.Color(77, 5, 77));
        guardianSSNLabel.setText("Guardian SSN");
        jPanel1.add(guardianSSNLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));
        jPanel1.add(guardianSSNTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 190, -1));

        guardianNameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        guardianNameLabel.setForeground(new java.awt.Color(77, 5, 77));
        guardianNameLabel.setText("Guardian Name");
        jPanel1.add(guardianNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));
        jPanel1.add(guardianNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, -1));

        SuppcardNumberLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        SuppcardNumberLabel.setForeground(new java.awt.Color(77, 5, 77));
        SuppcardNumberLabel.setText("Supplies Card Number ");
        jPanel1.add(SuppcardNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        jPanel1.add(suppCardNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 190, -1));

        affCardNumberLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        affCardNumberLabel.setForeground(new java.awt.Color(77, 5, 77));
        affCardNumberLabel.setText("Affairs Card Number");
        jPanel1.add(affCardNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));
        jPanel1.add(affCardNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 190, -1));

        finish.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        finish.setForeground(new java.awt.Color(77, 5, 77));
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        jPanel1.add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        backGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\back.jpg")); // NOI18N
        jPanel1.add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        interface2 jf = new interface2();
        jf.show();
        dispose();

    }//GEN-LAST:event_backActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        if (guardianSSNTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (guardianNameTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else {
             try {
                EntityManagerFactory emf =Persistence.createEntityManagerFactory("projectPU");
                EntityManager em =emf.createEntityManager();
                Requistp r=new Requistp();
                r.setGuardianSsn(this.guardianSSNTextField.getText());
                r.setGuardianName(this.guardianNameTextField.getText());
                r.setSuppliesCardNumber(this.suppCardNumberText.getText());
                r.setAffairsCodeNumber(this.affCardNumberText.getText());
                em.getTransaction().begin();
                em.persist(r);
                em.getTransaction().commit();
                emf.close();
                JOptionPane.showMessageDialog(null, "Your request has been sent successfully");
                interface1 jf = new interface1();
                jf.show();
                dispose();
        }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e.toString());
            }
    }//GEN-LAST:event_finishActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SuppcardNumberLabel;
    private javax.swing.JLabel affCardNumberLabel;
    private javax.swing.JTextField affCardNumberText;
    private javax.swing.JButton back;
    private javax.swing.JLabel backGround;
    private javax.swing.JButton finish;
    private javax.swing.JLabel guardianNameLabel;
    private javax.swing.JTextField guardianNameTextField;
    private javax.swing.JLabel guardianSSNLabel;
    private javax.swing.JTextField guardianSSNTextField;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel signUp;
    private javax.swing.JTextField suppCardNumberText;
    // End of variables declaration//GEN-END:variables
}
