/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author msys
 */
public class interface3 extends javax.swing.JFrame {

    /**
     * Creates new form interface3
     */
    public interface3() {
        initComponents();
    }
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        icon = new javax.swing.JLabel();
        signUp = new javax.swing.JLabel();
        universityNameLabel = new javax.swing.JLabel();
        universityNameTextField = new javax.swing.JTextField();
        universityLabel = new javax.swing.JLabel();
        universityMajorList = new javax.swing.JComboBox<>();
        yearOfGraduateLabel = new javax.swing.JLabel();
        yearOfGraduateTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        finish = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\BACK.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        icon.setBackground(new java.awt.Color(255, 204, 255));
        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\ICON.png")); // NOI18N
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        signUp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        signUp.setForeground(new java.awt.Color(77, 5, 77));
        signUp.setText("Sign Up of Employees");
        jPanel1.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 280, -1));

        universityNameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        universityNameLabel.setForeground(new java.awt.Color(77, 5, 77));
        universityNameLabel.setText("University Name");
        jPanel1.add(universityNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        universityNameTextField.setEditable(false);
        universityNameTextField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        universityNameTextField.setText("Al-Quds Open University ");
        universityNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                universityNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(universityNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 190, -1));

        universityLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        universityLabel.setForeground(new java.awt.Color(77, 5, 77));
        universityLabel.setText("University Major");
        jPanel1.add(universityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        universityMajorList.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        universityMajorList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Special Education", "Social Service", "Educational Psychology", "Medicine", "Nursing" }));
        universityMajorList.setToolTipText("");
        jPanel1.add(universityMajorList, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 190, -1));

        yearOfGraduateLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        yearOfGraduateLabel.setForeground(new java.awt.Color(77, 5, 77));
        yearOfGraduateLabel.setText("Year of Graduate");
        jPanel1.add(yearOfGraduateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        jPanel1.add(yearOfGraduateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 190, -1));

        emailLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(77, 5, 77));
        emailLabel.setText("Email");
        jPanel1.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 190, -1));

        finish.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        finish.setForeground(new java.awt.Color(77, 5, 77));
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        jPanel1.add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 235, -1, -1));

        backGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\back.jpg")); // NOI18N
        jPanel1.add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
         interface2 jf = new interface2();
         jf.show();
         dispose();
    }//GEN-LAST:event_backActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here: 
        if (yearOfGraduateTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (emailTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else {
            try {
            EntityManagerFactory emf =Persistence.createEntityManagerFactory("projectPU");
            EntityManager em =emf.createEntityManager();
            Requiste r=new Requiste();
            r.setUniversityName(this.universityNameTextField.getText());
            r.setUniversityMajor(this.universityMajorList.getToolTipText());
            r.setYearOfGraduate(Short.valueOf(this.yearOfGraduateTextField.getText()));
            r.setEMail(this.emailTextField.getText());
            em.getTransaction().begin();
            em.persist(r);
            em.getTransaction().commit();
            emf.close();
            JOptionPane.showMessageDialog(null, "Your request has been sent successfully");
            interface1 jf = new interface1();
            jf.show();
            dispose();
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_finishActionPerformed

    private void universityNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_universityNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_universityNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton finish;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel signUp;
    private javax.swing.JLabel universityLabel;
    private javax.swing.JComboBox<String> universityMajorList;
    private javax.swing.JLabel universityNameLabel;
    private javax.swing.JTextField universityNameTextField;
    private javax.swing.JLabel yearOfGraduateLabel;
    private javax.swing.JTextField yearOfGraduateTextField;
    // End of variables declaration//GEN-END:variables
}
