/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author msys
 */
public class interface4 extends javax.swing.JFrame {

    /**
     * Creates new form interface4
     */
    public interface4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signUp = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        universityNameLabel = new javax.swing.JLabel();
        universityNameTextField = new javax.swing.JTextField();
        universityMajorLabel = new javax.swing.JLabel();
        universityMajorList = new javax.swing.JComboBox<>();
        trainingHoursLabel = new javax.swing.JLabel();
        trainingHoursTextField = new javax.swing.JTextField();
        finish = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signUp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        signUp.setForeground(new java.awt.Color(77, 5, 77));
        signUp.setText("Sign Up Of Trainees");
        jPanel1.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\ICON.png")); // NOI18N
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\BACK.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        universityNameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        universityNameLabel.setForeground(new java.awt.Color(77, 5, 77));
        universityNameLabel.setText("University Name");
        jPanel1.add(universityNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        universityNameTextField.setEditable(false);
        universityNameTextField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        universityNameTextField.setText("Al-Quds Open University ");
        jPanel1.add(universityNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 190, -1));

        universityMajorLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        universityMajorLabel.setForeground(new java.awt.Color(77, 5, 77));
        universityMajorLabel.setText("University Major");
        jPanel1.add(universityMajorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        universityMajorList.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        universityMajorList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Special Education", "Social Service" }));
        jPanel1.add(universityMajorList, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 190, -1));

        trainingHoursLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        trainingHoursLabel.setForeground(new java.awt.Color(77, 5, 77));
        trainingHoursLabel.setText("Training Hours");
        jPanel1.add(trainingHoursLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        jPanel1.add(trainingHoursTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 190, -1));

        finish.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        finish.setForeground(new java.awt.Color(77, 5, 77));
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        jPanel1.add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        backGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\back.jpg")); // NOI18N
        jPanel1.add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        interface1 jf = new interface1();
         jf.show();
         dispose();
    }//GEN-LAST:event_backActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        if (trainingHoursTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else {
            try {
                EntityManagerFactory emf =Persistence.createEntityManagerFactory("projectPU");
                EntityManager em =emf.createEntityManager();
                Requistt r=new Requistt();
                r.setUniversityName(this.universityNameTextField.getText());
                r.setMajor(this.universityMajorList.getToolTipText());
                r.setTrainingHours(Short.valueOf(this.trainingHoursTextField.getText()));
                em.getTransaction().begin();
                em.persist(r);
                em.getTransaction().commit();
                emf.close();
               JOptionPane.showMessageDialog(null, "Your request has been sent successfully");
               interface1 jf = new interface1();
               jf.show();
               dispose();
        }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_finishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel backGround;
    private javax.swing.JButton finish;
    private javax.swing.JLabel icon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel signUp;
    private javax.swing.JLabel trainingHoursLabel;
    private javax.swing.JTextField trainingHoursTextField;
    private javax.swing.JLabel universityMajorLabel;
    private javax.swing.JComboBox<String> universityMajorList;
    private javax.swing.JLabel universityNameLabel;
    private javax.swing.JTextField universityNameTextField;
    // End of variables declaration//GEN-END:variables
}
