/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;

/**
 *
 * @author msys
 */
public class interface7 extends javax.swing.JFrame {

    /**
     * Creates new form interface7
     */
    public interface7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        signUpTools = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        nameToolLabel = new javax.swing.JLabel();
        nameToolList = new javax.swing.JComboBox<>();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        givenDateLabel = new javax.swing.JLabel();
        givenDateText = new com.toedter.calendar.JDateChooser();
        periodLabel = new javax.swing.JLabel();
        periodTextField = new javax.swing.JTextField();
        checkLabel = new javax.swing.JLabel();
        finish = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\ICON.png")); // NOI18N
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        signUpTools.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        signUpTools.setForeground(new java.awt.Color(77, 5, 77));
        signUpTools.setText("Sign Up To Tools");
        jPanel1.add(signUpTools, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\BACK.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        nameToolLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nameToolLabel.setForeground(new java.awt.Color(77, 5, 77));
        nameToolLabel.setText("Names of Tools");
        jPanel1.add(nameToolLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        nameToolList.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        nameToolList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wheel chair", "Electric wheelchair", "Crutches", "Bathroom chair" }));
        nameToolList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameToolListActionPerformed(evt);
            }
        });
        jPanel1.add(nameToolList, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 190, -1));

        idLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(77, 5, 77));
        idLabel.setText("ID");
        jPanel1.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));
        jPanel1.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 190, -1));

        givenDateLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        givenDateLabel.setForeground(new java.awt.Color(77, 5, 77));
        givenDateLabel.setText("Given Date");
        jPanel1.add(givenDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        jPanel1.add(givenDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 190, -1));

        periodLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        periodLabel.setForeground(new java.awt.Color(77, 5, 77));
        periodLabel.setText("Period");
        jPanel1.add(periodLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));
        jPanel1.add(periodTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 190, -1));

        checkLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkLabel.setForeground(new java.awt.Color(77, 5, 77));
        jPanel1.add(checkLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 190, -1));

        finish.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        finish.setForeground(new java.awt.Color(77, 5, 77));
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        jPanel1.add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        backGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\back.jpg")); // NOI18N
        jPanel1.add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameToolListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameToolListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameToolListActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        if (idTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (givenDateText.getDate().toString().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (periodTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else {
        JOptionPane.showMessageDialog(null, "Your request has been sent successfully");
        interface1 jf = new interface1();
        jf.show();
        dispose();
        }
    }//GEN-LAST:event_finishActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        pframe3 jf = new pframe3();
        jf.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel checkLabel;
    private javax.swing.JButton finish;
    private javax.swing.JLabel givenDateLabel;
    private com.toedter.calendar.JDateChooser givenDateText;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameToolLabel;
    private javax.swing.JComboBox<String> nameToolList;
    private javax.swing.JLabel periodLabel;
    private javax.swing.JTextField periodTextField;
    private javax.swing.JLabel signUpTools;
    // End of variables declaration//GEN-END:variables
}
