/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author msys
 */
public class interface2 extends javax.swing.JFrame {

    /**
     * Creates new form interface2
     */
    public interface2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mOrF = new javax.swing.ButtonGroup();
        eOrTorP = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        signUp = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        ssnlabel = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        firstNamelabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        secondNameLabel = new javax.swing.JLabel();
        SecondNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        streetLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        birthdayLabel = new javax.swing.JLabel();
        birthdaytext = new com.toedter.calendar.JDateChooser();
        genderLabel = new javax.swing.JLabel();
        maritaStatusLabel = new javax.swing.JLabel();
        maritalStatusTextField = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        fmale = new javax.swing.JRadioButton();
        chooseLabel = new javax.swing.JLabel();
        employee = new javax.swing.JRadioButton();
        trainees = new javax.swing.JRadioButton();
        patient = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\ICON.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        signUp.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        signUp.setForeground(new java.awt.Color(77, 5, 77));
        signUp.setText("Sign Up in Department  Disability");
        jPanel1.add(signUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 300, -1));

        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\BACK.png")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        ssnlabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ssnlabel.setForeground(new java.awt.Color(77, 5, 77));
        ssnlabel.setText("SSN");
        jPanel1.add(ssnlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 40, -1));
        jPanel1.add(ssnTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 190, -1));

        firstNamelabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        firstNamelabel.setForeground(new java.awt.Color(77, 5, 77));
        firstNamelabel.setText("First Name ");
        jPanel1.add(firstNamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));
        jPanel1.add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 190, -1));

        secondNameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        secondNameLabel.setForeground(new java.awt.Color(77, 5, 77));
        secondNameLabel.setText("Second Name");
        jPanel1.add(secondNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        SecondNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(SecondNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 190, -1));

        lastNameLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(77, 5, 77));
        lastNameLabel.setText("Last Name ");
        jPanel1.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));
        jPanel1.add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 190, -1));

        cityLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(77, 5, 77));
        cityLabel.setText("City");
        jPanel1.add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 50, -1));
        jPanel1.add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 190, -1));

        streetLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        streetLabel.setForeground(new java.awt.Color(77, 5, 77));
        streetLabel.setText("Street");
        jPanel1.add(streetLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        jPanel1.add(streetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 190, -1));

        phoneLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(77, 5, 77));
        phoneLabel.setText("Phone");
        jPanel1.add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));
        jPanel1.add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 190, -1));

        birthdayLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        birthdayLabel.setForeground(new java.awt.Color(77, 5, 77));
        birthdayLabel.setText("BirthDay");
        jPanel1.add(birthdayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));
        jPanel1.add(birthdaytext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 190, -1));

        genderLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(77, 5, 77));
        genderLabel.setText("Gender");
        jPanel1.add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, 20));

        maritaStatusLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        maritaStatusLabel.setForeground(new java.awt.Color(77, 5, 77));
        maritaStatusLabel.setText("Marital Status");
        jPanel1.add(maritaStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));
        jPanel1.add(maritalStatusTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 190, -1));

        mOrF.add(male);
        male.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        male.setForeground(new java.awt.Color(77, 5, 77));
        male.setLabel("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        mOrF.add(fmale);
        fmale.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        fmale.setForeground(new java.awt.Color(77, 5, 77));
        fmale.setText("Fmale");
        jPanel1.add(fmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        chooseLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        chooseLabel.setForeground(new java.awt.Color(77, 5, 77));
        chooseLabel.setText("Choose ");
        jPanel1.add(chooseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        eOrTorP.add(employee);
        employee.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        employee.setForeground(new java.awt.Color(77, 5, 77));
        employee.setText("Employees");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        jPanel1.add(employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        eOrTorP.add(trainees);
        trainees.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        trainees.setForeground(new java.awt.Color(77, 5, 77));
        trainees.setText("Trainees");
        jPanel1.add(trainees, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        eOrTorP.add(patient);
        patient.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        patient.setForeground(new java.awt.Color(77, 5, 77));
        patient.setText("Patient");
        jPanel1.add(patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        next.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        next.setForeground(new java.awt.Color(77, 5, 77));
        next.setText("Next");
        next.setActionCommand("");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        backGround.setIcon(new javax.swing.ImageIcon("C:\\Users\\msys\\Desktop\\project\\src\\project\\back.jpg")); // NOI18N
        jPanel1.add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        interface1 jf = new interface1();
        jf.show();
        dispose();

    }//GEN-LAST:event_backActionPerformed

    private void SecondNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondNameTextFieldActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        if (ssnTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (firstNameTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (SecondNameTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (lastNameTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (cityTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (streetTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (phoneTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (birthdaytext.getDate().toString().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (maritalStatusTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (!(male.isSelected())&&(!(fmale.isSelected()))){
            JOptionPane.showMessageDialog(null, "You must fill in all fields");
        }
        else if (!(employee.isSelected())&&(!(trainees.isSelected())&&(!(patient.isSelected())))){
            JOptionPane.showMessageDialog(null, "You must fill in all fields"); 
        } 
        if (employee.isSelected()){
             interface3 jf = new interface3();
              jf.show();
              dispose();
        }
        else if (trainees.isSelected()){
             interface4 jf = new interface4();
             jf.show();
             dispose();
        }
        else if (patient.isSelected()){
             interface5 jf = new interface5();
             jf.show();
             dispose();
        }
        try {
           EntityManagerFactory emf =Persistence.createEntityManagerFactory("projectPU");
           EntityManager em =emf.createEntityManager();
           Members M1= new Members();
           M1.setSsn(this.ssnTextField.getText());
           M1.setFirstName(this.firstNameTextField.getText());
           M1.setMinitName(this.SecondNameTextField.getText());
           M1.setLastName(this.lastNameTextField.getText());
           M1.setCity(this.cityTextField.getText());
           M1.setStreet(this.streetTextField.getText());
           M1.setPhone(this.phoneTextField.getText());
           //M1.setBithdate(this.birthdayTextField.getText());
           M1.setMaritalStatus(this.maritalStatusTextField.getText());
           if (male .isSelected()){
               M1.setGender("m");
           }
           else if (fmale.isSelected()){
               M1.setGender("f");
           }
           em.getTransaction().begin();
           em.persist(M1);
           em.getTransaction().commit();
           emf.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SecondNameTextField;
    private javax.swing.JButton back;
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel birthdayLabel;
    private com.toedter.calendar.JDateChooser birthdaytext;
    private javax.swing.JLabel chooseLabel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.ButtonGroup eOrTorP;
    private javax.swing.JRadioButton employee;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel firstNamelabel;
    private javax.swing.JRadioButton fmale;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.ButtonGroup mOrF;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel maritaStatusLabel;
    private javax.swing.JTextField maritalStatusTextField;
    private javax.swing.JButton next;
    private javax.swing.JRadioButton patient;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel secondNameLabel;
    private javax.swing.JLabel signUp;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JLabel ssnlabel;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JRadioButton trainees;
    // End of variables declaration//GEN-END:variables
}
